### ISSUE TITLE
Bug exemple V0

### ISSUE THREAD

**Issue by JulioJu** [AlexDmr/bshm#1]
Bonjour,

L'exemple V0 ne fonctionne pas chez moi. 

Au démarrage de node (`node mainV0.js`) j'ai l'erreur suivante : 

```
/home/(…)/Documents_Linux/DCISS/langageEtTechnoWeb2/AngularJs/bshm/Liste/V0/mainV0.js:3
  , angular-material    = require( "angular-material"           )
           ^
SyntaxError: Unexpected token -
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

Gulp me sort également l'erreur non fatale suivante:

```
[15:51:56] Error in plugin 'gulp-webpack'
Message:
    Path doesn't exist '/home/(…)/Documents_Linux/DCISS/langageEtTechnoWeb2/AngularJs/bshm/Liste/V0/76ece425ab20a1463715.js'
[15:51:56] [object Object]
[15:51:56] webpack is watching for changes
```

Comme pour l'exemple V1, `npm install` me sort les warnings suivants (mais qui ne semblent pas poser problème pour le projet amorcePAI) : 

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN v0@1.0.0 No description
npm WARN v0@1.0.0 No repository field.
```

Je suis sous Arch Linux.

J'ai peut-être loupé quelque chose ?

Bien cordialement

Julio

**Comment by AlexDmr** [comment]
Les exemples fournis ne sont pas prévus pour s'exécuter dans un environnement NodeJS mais seulement dans un navigateur. 
Après avoir fait npm install pui gulp, il faut simplement ouvrir le ficheir index?html dans un navigateur (par glisser/déposer par exemple)

**Comment by JulioJu** [comment]
Merci !

Oui, il faut ouvrir le fichier liste.html. J'aurais dû m'en apercevoir si j'avais mieux regardé le code.

Julio
